repos:
  - repo: local
    hooks:
      - id: python-utf8
        name: python-utf8
        entry: bash -c "export PYTHONUTF8=1"
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: pretty-format-json
        args: [--no-sort-keys, --autofix, --no-ensure-ascii]
      - id: check-json
      - id: check-toml
      - id: check-yaml
        types: [yaml]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
    exclude: uv.lock
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
     - id: gitlint
       # run pre-commit install --hook-type commit-msg
       args: [--ignore, "B6", --msg-filename]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.9
    hooks:
      - id: actionlint
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
     - id: python-no-log-warn
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
     - id: ruff-format
     - id: ruff-check
